[FYERS]
client_id = YOUR_CLIENT_ID
secret_key = YOUR_SECRET_KEY
redirect_uri = http://localhost:3000/
# Note: The access token will be generated and stored here automatically
access_token =

[SETTINGS]
# Trade mode can be 'paper' or 'live'
trade_mode = paper
# File paths for data storage
potential_trades_csv = data/potential_trades.csv
open_positions_csv = data/open_positions.csv
trades_to_execute_txt = data/trades_to_execute.txt
nifty50_url = https://archives.nseindia.com/content/indices/ind_nifty50list.csv
fno_url = https://archives.nseindia.com/content/fo/fo_mktlots.csv

[LOGGING]
log_file = logs/strategy.log
